export const ErrorCodes = {
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    NETWORK_CONNECTION_FAILED: "NETWORK_CONNECTION_FAILED",
    NETWORK_TIMEOUT: "NETWORK_TIMEOUT",
    VALIDATION_INVALID_DATA: "VALIDATION_INVALID_DATA",
    VALIDATION_REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];